"""Reference ranges configuration and lookup functions."""
from typing import Optional
from app.models.schemas import ReferenceRangeModel

# Core Reference Ranges available locally
LOCAL_REFERENCE_RANGES: dict[str, dict] = {
    "hemoglobin": {
        "canonical_name": "Hemoglobin",
        "unit": "g/dL",
        "normal_min": 13.5,
        "normal_max": 17.5,
        "warning_min": 10.0,
        "warning_max": 19.0,
        "critical_min": 7.0,
        "critical_max": 20.0,
        "description": "Oxygen-carrying protein in red blood cells.",
    },
    "glucose": {
        "canonical_name": "Fasting Glucose",
        "unit": "mg/dL",
        "normal_min": 70.0,
        "normal_max": 99.0,
        "warning_min": 54.0,
        "warning_max": 199.0,
        "critical_min": 54.0,
        "critical_max": 300.0,
        "description": "Primary blood sugar regulating cellular energy.",
    },
    "potassium": {
        "canonical_name": "Serum Potassium",
        "unit": "mmol/L",
        "normal_min": 3.5,
        "normal_max": 5.0,
        "warning_min": 3.0,
        "warning_max": 5.5,
        "critical_min": 2.8,
        "critical_max": 6.2,
        "description": "Vital electrolyte for cardiac and neuromuscular function.",
    },
    "platelets": {
        "canonical_name": "Platelets",
        "unit": "cells/uL",
        "normal_min": 150000.0,
        "normal_max": 450000.0,
        "warning_min": 100000.0,
        "warning_max": 600000.0,
        "critical_min": 50000.0,
        "critical_max": 1000000.0,
        "description": "Blood cells essential for normal clot formation.",
    },
    "sodium": {
        "canonical_name": "Serum Sodium",
        "unit": "mmol/L",
        "normal_min": 135.0,
        "normal_max": 145.0,
        "warning_min": 130.0,
        "warning_max": 150.0,
        "critical_min": 120.0,
        "critical_max": 160.0,
        "description": "Major extracellular electrolyte maintaining fluid balance.",
    },
    "creatinine": {
        "canonical_name": "Serum Creatinine",
        "unit": "mg/dL",
        "normal_min": 0.6,
        "normal_max": 1.2,
        "warning_min": 0.4,
        "warning_max": 2.5,
        "critical_min": 0.2,
        "critical_max": 4.0,
        "description": "Muscle breakdown byproduct used to evaluate renal function.",
    },
    "wbc": {
        "canonical_name": "White Blood Cell Count (WBC)",
        "unit": "cells/uL",
        "normal_min": 4500.0,
        "normal_max": 11000.0,
        "warning_min": 3000.0,
        "warning_max": 15000.0,
        "critical_min": 2000.0,
        "critical_max": 30000.0,
        "description": "Immune cells protecting against infection and inflammation.",
    },
    "calcium": {
        "canonical_name": "Serum Calcium",
        "unit": "mg/dL",
        "normal_min": 8.5,
        "normal_max": 10.2,
        "warning_min": 7.5,
        "warning_max": 11.5,
        "critical_min": 6.5,
        "critical_max": 13.0,
        "description": "Mineral critical for bone health, muscle contractions, and nerve signaling.",
    },
    "bun": {
        "canonical_name": "Blood Urea Nitrogen (BUN)",
        "unit": "mg/dL",
        "normal_min": 7.0,
        "normal_max": 20.0,
        "warning_min": 5.0,
        "warning_max": 40.0,
        "critical_min": 3.0,
        "critical_max": 60.0,
        "description": "Protein breakdown waste product cleared by kidneys.",
    },
    "alt": {
        "canonical_name": "ALT (Alanine Aminotransferase)",
        "unit": "U/L",
        "normal_min": 7.0,
        "normal_max": 56.0,
        "warning_min": 5.0,
        "warning_max": 150.0,
        "critical_min": 0.0,
        "critical_max": 300.0,
        "description": "Enzyme concentrated primarily in liver cells.",
    },
    "ast": {
        "canonical_name": "AST (Aspartate Aminotransferase)",
        "unit": "U/L",
        "normal_min": 10.0,
        "normal_max": 40.0,
        "warning_min": 5.0,
        "warning_max": 120.0,
        "critical_min": 0.0,
        "critical_max": 250.0,
        "description": "Enzyme found in liver, heart, and muscle tissue.",
    },
    "bilirubin": {
        "canonical_name": "Total Bilirubin",
        "unit": "mg/dL",
        "normal_min": 0.2,
        "normal_max": 1.2,
        "warning_min": 0.1,
        "warning_max": 3.0,
        "critical_min": 0.0,
        "critical_max": 5.0,
        "description": "Yellow pigment produced during normal breakdown of red blood cells.",
    },
}

# Extended catalog hosted by the MCP server (can also be queried when not in local)
MCP_EXTENDED_RANGES: dict[str, dict] = {
    "cholesterol": {
        "canonical_name": "Total Cholesterol",
        "unit": "mg/dL",
        "normal_min": 125.0,
        "normal_max": 200.0,
        "warning_min": 100.0,
        "warning_max": 240.0,
        "critical_min": 70.0,
        "critical_max": 350.0,
        "description": "Total circulating lipid profile component.",
    },
    "hba1c": {
        "canonical_name": "Hemoglobin A1c",
        "unit": "%",
        "normal_min": 4.0,
        "normal_max": 5.6,
        "warning_min": 3.5,
        "warning_max": 8.5,
        "critical_min": 3.0,
        "critical_max": 12.0,
        "description": "Average blood glucose over the preceding 2-3 months.",
    },
    "tsh": {
        "canonical_name": "Thyroid Stimulating Hormone (TSH)",
        "unit": "uIU/mL",
        "normal_min": 0.4,
        "normal_max": 4.0,
        "warning_min": 0.1,
        "warning_max": 10.0,
        "critical_min": 0.01,
        "critical_max": 20.0,
        "description": "Pituitary hormone regulating thyroid function.",
    },
    "troponin": {
        "canonical_name": "Troponin I",
        "unit": "ng/mL",
        "normal_min": 0.0,
        "normal_max": 0.04,
        "warning_min": 0.0,
        "warning_max": 0.4,
        "critical_min": 0.0,
        "critical_max": 1.5,
        "description": "Cardiac biomarker indicative of myocardial injury.",
    },
    "ferritin": {
        "canonical_name": "Serum Ferritin",
        "unit": "ng/mL",
        "normal_min": 30.0,
        "normal_max": 400.0,
        "warning_min": 15.0,
        "warning_max": 700.0,
        "critical_min": 10.0,
        "critical_max": 1500.0,
        "description": "Major cellular storage protein for iron.",
    },
}

# Aliases mapping common synonyms to canonical keys
TEST_ALIASES: dict[str, str] = {
    "hgb": "hemoglobin",
    "hb": "hemoglobin",
    "hemoglobin": "hemoglobin",
    "glucose": "glucose",
    "glu": "glucose",
    "blood sugar": "glucose",
    "fasting glucose": "glucose",
    "potassium": "potassium",
    "k": "potassium",
    "k+": "potassium",
    "platelets": "platelets",
    "plt": "platelets",
    "platelet": "platelets",
    "platelet count": "platelets",
    "sodium": "sodium",
    "na": "sodium",
    "na+": "sodium",
    "creatinine": "creatinine",
    "creat": "creatinine",
    "cr": "creatinine",
    "wbc": "wbc",
    "white blood cell": "wbc",
    "white blood cells": "wbc",
    "white blood cell count": "wbc",
    "calcium": "calcium",
    "ca": "calcium",
    "ca++": "calcium",
    "bun": "bun",
    "blood urea nitrogen": "bun",
    "urea": "bun",
    "alt": "alt",
    "sgpt": "alt",
    "ast": "ast",
    "sgot": "ast",
    "bilirubin": "bilirubin",
    "total bilirubin": "bilirubin",
    "bili": "bilirubin",
    "cholesterol": "cholesterol",
    "total cholesterol": "cholesterol",
    "hba1c": "hba1c",
    "a1c": "hba1c",
    "glycated hemoglobin": "hba1c",
    "tsh": "tsh",
    "troponin": "troponin",
    "troponin i": "troponin",
    "ferritin": "ferritin",
}


def normalize_test_name(name: str) -> str:
    """Normalize input test name to clean lookup key."""
    cleaned = name.lower().strip()
    cleaned = cleaned.replace("_", " ").replace("-", " ")
    cleaned = " ".join(cleaned.split())
    return TEST_ALIASES.get(cleaned, cleaned)


def get_local_reference_range(test_name: str) -> Optional[ReferenceRangeModel]:
    """Retrieve reference range from local dictionary."""
    key = normalize_test_name(test_name)
    data = LOCAL_REFERENCE_RANGES.get(key)
    if not data:
        return None
    return ReferenceRangeModel(
        test_name=data.get("canonical_name", test_name),
        unit=data["unit"],
        normal_min=data["normal_min"],
        normal_max=data["normal_max"],
        warning_min=data["warning_min"],
        warning_max=data["warning_max"],
        critical_min=data["critical_min"],
        critical_max=data["critical_max"],
        description=data.get("description"),
    )
